/sim_node:
  ros__parameters:
    camera_resolution: 1.0
    cam_hz: 20.0
    fov: 34.68
    lidar_enable: false
    lidar_hz: 5.5
    sim_speed: 1.0
/viewer_node:
  ros__parameters:
    viewer_topic: /drawn_image

