/sim_node:
  ros__parameters:
    enable_cv_cam: false
    cv_resolution_x: 1920
    cv_resolution_y: 1200
    cv_fov_horizontal: 31
    cv_fov_vertical: 20
    cv_exposure: 0.005
    cv_ray_tracing: false

    enable_lidar: true
    lidar_pointcloud_resolution: 20
    lidar_test_arg: 5

    spawn_scenario: "center_1v1"
    human_gui: true